### ISSUE TITLE
add warning to GNOME-software

### ISSUE THREAD

**Issue by Itai-Nelken** [ryanfortner/pi-bashscripts-files#1]
installing gnome-software uninstalls add/remove software (in RPiOS) so add a warning that on RPiOS and RPiOS based OS's like TwisterOS, installing gnome-software will delete add/remove software. to install it back run `sudo apt install pi-package` (that will uninstall gnome-software).

**Comment by ryanfortner** [comment]
This is very helpful. Thank you for letting me know.
