### ISSUE TITLE
OBS Studio

### ISSUE THREAD

**Issue by techcoder20** [ryanfortner/pi-bashscripts-files#10]
I made a installation script for obs but it is only for 32 bit right now. I thought u could add it the scripts

Installation Command:
`wget -qO- https://raw.githubusercontent.com/techcoder20/RPIObsInstaller/main/install.sh | bash`

Uninstallation Command:
`wget -qO- https://raw.githubusercontent.com/techcoder20/RPIObsInstaller/main/uninstall.sh | bash`

**Comment by Itai-Nelken** [comment]
@techcoder20 added a 64bit install script, so the install script linked above doesn't exist. here are updated links:

**32bit:**<br>
`wget -qO- https://raw.githubusercontent.com/techcoder20/RPIObsInstaller/main/install-32.sh | bash`

**64bit:**<br>
`wget -qO- https://raw.githubusercontent.com/techcoder20/RPIObsInstaller/main/install-64.sh | bash`

**uninstall (same as above):**<br>
`wget -qO- https://raw.githubusercontent.com/techcoder20/RPIObsInstaller/main/uninstall.sh | bash`

**Comment by ryanfortner** [comment]
@Itai-Nelken @techcoder20 i totally forgot to add them  i am doing it now

**Comment by ryanfortner** [comment]
Done.
