### ISSUE TITLE
Full ATlauncherPI installer (works correctly now)

### ISSUE THREAD

**Issue by pi-dev500** [ryanfortner/pi-bashscripts-files#11]
@chunky-milk I have the full pi-apps atlauncher package. I think It works on all systems for rpi and l have tested It on raspbios.
[ATlauncherPI](https://github.com/pi-dev500/MinecraftMicrosoftPILauncher)

**Comment by pi-dev500** [comment]
The splash isn't the original.

**Comment by chunky-milk** [comment]
I can test it and make sure it works.

**Comment by ryanfortner** [comment]
@pi-dev500 are you sure it actually works? I don't think atlauncher uses launcher_profiles.json

**Comment by pi-dev500** [comment]
It's possible, but the launchers that I have tried generate this file :
Tlauncher, latest launcher for Minecraft and the legacy launcher.
(I have a 64bits amd64 and a pi)

**Comment by pi-dev500** [comment]
I am going to remove .minecraft and launch Atlauncher if that generate the file, that works.

**Comment by pi-dev500** [comment]
That must work now. I have updated it.
configs files:
[ATconfigs.zip](https://github.com/chunky-milk/pi-bashscripts-files/files/5886306/ATconfigs.zip)
pi-apps zip:
[ATlauncherPI.zip](https://github.com/chunky-milk/pi-bashscripts-files/files/5886311/ATlauncherPI.zip)

**Comment by pi-dev500** [comment]
You can retry installation now. I have added  the configurations files of Atlauncher. Link of configuration files for Atlauncher: [link](https://github.com/pi-dev500/MinecraftMicrosoftPILauncher/tree/main/ATconfigs)
New zipfile: 
[ATlauncherPI.zip](https://github.com/chunky-milk/pi-bashscripts-files/files/5888654/ATlauncherPI.zip)

**Comment by pi-dev500** [comment]
My repos is also availlable.

**Comment by pi-dev500** [comment]
For updates, there is no problems, that's auto-updated so my jarfile is always up-to-date

**Comment by pi-dev500** [comment]
~~@pi-dev500 are you sure it actually works? I don't think atlauncher uses launcher_profiles.json~~

**Comment by pi-dev500** [comment]
It don't use launcher_profiles.json .

**Comment by pi-dev500** [comment]
@chunky-milk I'm now done with the script .It works fine on my raspberry pi 4 . I use the old custom jvm argument in ~/.local/share/ATlauncher/jarfile/configs/ATlauncher.json . Please use my repository: the zipfile of this issue is outdated.

**Comment by ryanfortner** [comment]
> @chunky-milk I'm now done with the script .It works fine on my raspberry pi 4 . I use the old custom jvm argument in ~/.local/share/ATlauncher/jarfile/configs/ATlauncher.json . Please use my repository: the zipfile of this issue is outdated.

ok sounds good.

**Comment by ryanfortner** [comment]
@pi-dev500 i added it. you should bring this up to the Pi-Apps developers, they mentioned needing a script.
