### ISSUE TITLE
Port this to Pi-Apps

### ISSUE THREAD

**Issue by ghost** [ryanfortner/pi-bashscripts-files#16]
[FirefoxBrowserPiApps.zip](https://github.com/chunky-milk/pi-bashscripts-files/files/6340724/FirefoxBrowserPiApps.zip)

**Comment by CleanMachine1** [comment]
1. Wrong place
2. Apt has firefox
3. Go to Pi-apps

**Comment by ryanfortner** [comment]
> 1. Wrong place
> 3. Go to Pi-apps

I agree, this is the wrong place to discuss this, especially if you want it on Pi Apps. 

> 2. Apt has firefox

`firefox-esr` is on apt, which is severely outdated, but the latest `firefox` is not.

**Comment by CleanMachine1** [comment]
So 
```bash
sudo apt install firefox #Is good?
#While
sudo apt install firefox-esr #Is bad

**Comment by ryanfortner** [comment]
> So
> 
> ```shell
> sudo apt install firefox #Is good?
> #While
> sudo apt install firefox-esr #Is bad
> ```

Try `sudo apt install firefox`, and see if it works.

**Comment by CleanMachine1** [comment]
Package: firefox
>State: not a real package (virtual)
N: Can't select candidate version from package firefox as it has no candidate
N: Can't select versions from package 'firefox' as it is purely virtual
N: No packages found


It works on my LM machine though :+1:

**Comment by ghost** [comment]
> Package: firefox
> 
> > State: not a real package (virtual)
> > N: Can't select candidate version from package firefox as it has no candidate
> > N: Can't select versions from package 'firefox' as it is purely virtual
> > N: No packages found
> 
> It works on my LM machine though 👍

Thats Linux Mint Firefox is in apt for that

Firefox is not in apt on debian based distributions on arm/arm64 based device

Firefox is in apt on Ubuntu on Raspberry Pi 4
Firefox Latest Version should be easily accessible on Raspberry Pi OS

**Comment by CleanMachine1** [comment]
@ObsidianOS7 this repo isn't really related to pi-apps

**Comment by ryanfortner** [comment]
@ObsidianOS7 I am going to close this. If you want it added to pi-apps then you need to _open an issue on pi apps_. Have a nice day 😄
