### ISSUE TITLE
Firefox issue + suggestion about it

### ISSUE THREAD

**Issue by Itai-Nelken** [ryanfortner/pi-bashscripts-files#3]
I think it started crashing when I logged in, so maybe add a warning to it's readme that it might be unstable?

**Comment by ryanfortner** [comment]
Good idea. Are you on a 32 or 64 bit operating system? because it works well for me on RPiOS/32bit

**Comment by Itai-Nelken** [comment]
> Good idea. Are you on a 32 or 64 bit operating system? because it works well for me on RPiOS/32bit

I'm on TwisterOS, so 32bit.
