### ISSUE TITLE
Deb file for panther launcher

### ISSUE THREAD

**Issue by techcoder20** [ryanfortner/pi-bashscripts-files#9]
I have made a deb file for panther launcher which you could use. Also botspot denied adding panther launcher to pi apps as we already have light pad and ulauncher

Here is the link: https://github.com/techcoder20/MacOSBigSurThemeConverter/blob/main/assets/panther-launcher_armhf.deb

**Comment by ryanfortner** [comment]
Okay cool I can add it.

**Comment by techcoder20** [comment]
Thanks

**Comment by ryanfortner** [comment]
Done.
